services:
  app:
    image: great # spring boot application container name
    build:
      context: . # Build the Dockerfile from the current directory
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080" # Map internal port 8084 to external 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
