services:
  app:
    image: spring-boot-concurrencyapp # spring boot application container name
    build:
      context: . # Build the Dockerfile from the current directory
    environment:
      DB_URL: jdbc:postgresql://db:5432/multithreading
      DB_USERNAME: postgres
      DB_PASSWORD: duaSHKH!229
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8084
    ports:
      - "8084:8084" # Map internal port 8084 to external 8084
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:14-alpine # PostgreSQL version
    environment:
      POSTGRES_DB: multithreading
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duaSHKH!229
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    ports:
      - "5431:5432" # Expose PostgreSQL port
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6378:6379" # Expose Redis port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    # driver: local Implicitly works without specifying
